### ISSUE TITLE
set scaling factor too

### ISSUE THREAD

**Issue by rubo77** [rubo77/set_resolution.py#3]
If you change the resolution you should also change the scaling factor.

If the new resolution is **half the resolution** like the current and the **current scaling-factor  is 2**, then it should be set by 

```
/usr/bin/gsettings set org.gnome.desktop.interface scaling-factor 1
/usr/bin/gsettings set com.ubuntu.user-interface scale-factor "{'HDMI1': 8, 'eDP1': 8}"
```

otherwise, it should be set **back to 2** by

```
/usr/bin/gsettings set org.gnome.desktop.interface scaling-factor 2
/usr/bin/gsettings set com.ubuntu.user-interface scale-factor "{'HDMI1': 8, 'eDP1': 16}"
```

**Comment by christopherlovell** [comment]
fixed in #9
